language: ruby
rvm:
  - 2.2

before_script:
  - gem install asciidoctor
  - gem install --pre asciidoctor-pdf
  - asciidoctor -v
  - asciidoctor-pdf -v

script:
  - asciidoctor src/index.adoc -D build/
  - asciidoctor-pdf src/index.adoc -D build/

after_script:
  # push output to gh-page
  - ls -l build/
